import React, { useEffect, useState } from 'react';
import { BookOpen, Plus, Save } from 'lucide-react';
import { PageHeader } from '../components/common/PageHeader';
import { RoleGuard } from '../components/common/RoleGuard';
import { useApp } from '../context/AppContext';

type Article = { id: string; title: string; category: string; content: string; visibleRoles: string; active: boolean; updatedAt: string };
const roles = ['ALL', 'ESTUDIANTE', 'DOCENTE', 'ADMIN', 'REGISTRO', 'FINANZAS', 'BIBLIOTECA', 'PARQUEO', 'EVENTOS'];

export const AssistantKnowledgePage: React.FC = () => {
  const { showToast } = useApp();
  const [items, setItems] = useState<Article[]>([]);
  const [form, setForm] = useState({ title: '', category: 'Proceso', content: '', visibleRoles: 'ALL' });
  const load = async () => { const response = await fetch('/api/assistant/knowledge'); if (response.ok) setItems(await response.json()); };
  useEffect(() => { void load(); }, []);
  const create = async (event: React.FormEvent) => { event.preventDefault(); const response = await fetch('/api/assistant/knowledge', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ ...form, visibleRoles: form.visibleRoles === 'ALL' ? [] : [form.visibleRoles] }) }); const data = await response.json(); if (!response.ok) return showToast(data.message || 'No se pudo guardar', 'error'); setForm({ title: '', category: 'Proceso', content: '', visibleRoles: 'ALL' }); showToast('Artículo agregado a la base de conocimiento', 'success'); await load(); };
  const toggle = async (article: Article) => { const response = await fetch(`/api/assistant/knowledge/${article.id}`, { method: 'PATCH', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ active: !article.active }) }); if (!response.ok) return showToast('No se pudo actualizar el artículo', 'error'); await load(); };
  const edit = async (article: Article) => { const title = window.prompt('Título', article.title); if (title === null) return; const category = window.prompt('Categoría', article.category); if (category === null) return; const content = window.prompt('Contenido', article.content); if (content === null) return; const response = await fetch(`/api/assistant/knowledge/${article.id}`, { method: 'PATCH', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ title, category, content }) }); if (!response.ok) return showToast('No se pudo editar el artículo', 'error'); showToast('Artículo actualizado', 'success'); await load(); };
  return <RoleGuard allowedRoles={['ADMIN', 'REGISTRO']}><div className="space-y-6"><PageHeader title="Base de conocimiento del asistente" description="Reglamentos, procesos, manuales y preguntas frecuentes. Solo se usan artículos autorizados para cada rol." breadcrumbs={[{ label: 'Inicio', href: '/dashboard' }, { label: 'Base de conocimiento', active: true }]} />
    <form onSubmit={create} className="grid gap-4 rounded-xl border bg-white p-5 shadow-xs md:grid-cols-2"><div className="md:col-span-2 flex items-center gap-2"><Plus className="h-5 w-5 text-[#800020]"/><h2 className="text-sm font-bold">Nuevo artículo</h2></div><input required minLength={3} value={form.title} onChange={(e) => setForm({ ...form, title: e.target.value })} placeholder="Título" className="rounded-lg border px-3 py-2 text-sm"/><div className="grid grid-cols-2 gap-3"><input required minLength={3} value={form.category} onChange={(e) => setForm({ ...form, category: e.target.value })} placeholder="Categoría" className="rounded-lg border px-3 py-2 text-sm"/><select value={form.visibleRoles} onChange={(e) => setForm({ ...form, visibleRoles: e.target.value })} className="rounded-lg border px-3 py-2 text-sm">{roles.map((role) => <option key={role}>{role}</option>)}</select></div><textarea required minLength={10} rows={7} value={form.content} onChange={(e) => setForm({ ...form, content: e.target.value })} placeholder="Contenido verificado del reglamento, proceso, manual o FAQ." className="rounded-lg border px-3 py-2 text-sm md:col-span-2"/><div className="md:col-span-2 flex justify-end"><button className="flex items-center gap-2 rounded-lg bg-[#800020] px-4 py-2 text-xs font-bold text-white"><Save className="h-4 w-4"/>Guardar artículo</button></div></form>
    <section className="overflow-hidden rounded-xl border bg-white"><div className="border-b p-5"><div className="flex items-center gap-2"><BookOpen className="h-5 w-5 text-[#800020]"/><h2 className="text-sm font-bold">Artículos publicados</h2></div></div>{items.length === 0 ? <p className="p-6 text-sm text-[#64748B]">Aún no hay artículos.</p> : <div className="divide-y">{items.map((article) => <article key={article.id} className="p-5"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="font-bold">{article.title}</p><p className="mt-1 text-xs text-[#64748B]">{article.category} · Visible para: {article.visibleRoles}</p></div><div className="flex gap-2"><button onClick={() => void edit(article)} className="rounded-lg border px-3 py-1.5 text-xs font-bold text-slate-700">Editar</button><button onClick={() => void toggle(article)} className={`rounded-lg px-3 py-1.5 text-xs font-bold ${article.active ? 'bg-green-50 text-green-700' : 'bg-slate-100 text-slate-600'}`}>{article.active ? 'Publicado' : 'Desactivado'}</button></div></div><p className="mt-3 whitespace-pre-wrap text-sm text-slate-700">{article.content}</p></article>)}</div>}</section>
  </div></RoleGuard>;
};
