import React, { useCallback, useEffect, useMemo, useState } from 'react';
import { AlertTriangle, BookOpenCheck, GripVertical, Save } from 'lucide-react';
import { PageHeader } from '../components/common/PageHeader';
import { RoleGuard } from '../components/common/RoleGuard';
import { useApp } from '../context/AppContext';

interface OrganizerCourse { code: string; name: string; credits: number; semester: number; prerequisites: { code: string; name: string }[]; }
interface OrganizerPlan { id: string; code: string; name: string; version: string; careerId: string; status: string; durationSemesters: number; totalCredits: number; courses: OrganizerCourse[]; }
interface OrganizerData { careers: { code: string; name: string }[]; plans: OrganizerPlan[]; }

export const CurriculumOrganizerPage: React.FC = () => {
  const { showToast } = useApp();
  const [data, setData] = useState<OrganizerData>({ careers: [], plans: [] });
  const [careerId, setCareerId] = useState('');
  const [planId, setPlanId] = useState('');
  const [duration, setDuration] = useState(8);
  const [assignments, setAssignments] = useState<Record<string, number>>({});
  const [dragging, setDragging] = useState<string | null>(null);
  const [saving, setSaving] = useState(false);

  const load = useCallback(async () => { const response = await fetch('/api/curriculum-plans/organizer'), result = await response.json(); if (!response.ok) return showToast(result.message, 'error'); setData(result); const firstCareer = result.careers[0]?.code || ''; setCareerId((current) => current || firstCareer); }, [showToast]);
  useEffect(() => { load(); }, [load]);
  const careerPlans = useMemo(() => data.plans.filter((plan) => plan.careerId === careerId), [careerId, data.plans]);
  useEffect(() => { if (!careerPlans.some((plan) => plan.id === planId)) setPlanId(careerPlans[0]?.id || ''); }, [careerPlans, planId]);
  const plan = useMemo(() => data.plans.find((item) => item.id === planId) || null, [data.plans, planId]);
  useEffect(() => { if (!plan) return; setDuration(plan.durationSemesters); setAssignments(Object.fromEntries(plan.courses.map((course) => [course.code, course.semester]))); }, [plan]);
  const issues = useMemo(() => { if (!plan) return []; return plan.courses.flatMap((course) => course.prerequisites.flatMap((prerequisite) => { const prerequisiteSemester = assignments[prerequisite.code], courseSemester = assignments[course.code]; return prerequisiteSemester && courseSemester && prerequisiteSemester >= courseSemester ? [{ courseCode: course.code, prerequisiteCode: prerequisite.code, message: `${prerequisite.code} debe estar antes que ${course.code}` }] : []; })); }, [assignments, plan]);
  const moveCourse = (courseCode: string, semester: number) => { setAssignments((current) => ({ ...current, [courseCode]: semester })); setDragging(null); };
  const changeDuration = (value: number) => { const next = Math.max(1, Math.min(12, value || 1)), previous = duration; setDuration(next); if (next < previous) setAssignments((current) => Object.fromEntries(Object.entries(current).map(([code, semester]) => [code, Math.min(semester, next)]))); };
  const save = async () => { if (!plan || issues.length) return showToast('Corrige los prerrequisitos marcados antes de guardar', 'warning'); setSaving(true); const response = await fetch(`/api/curriculum-plans/${plan.id}/layout`, { method: 'PATCH', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ durationSemesters: duration, assignments: Object.entries(assignments).map(([courseCode, semester]) => ({ courseCode, semester })) }) }); const result = await response.json(); setSaving(false); if (!response.ok) return showToast(result.message, 'error'); showToast(result.message, 'success'); await load(); };

  return <RoleGuard allowedRoles={['ADMIN']}><div className="space-y-6"><PageHeader title="Organizar Pensum" description="Distribuye los cursos por semestre y valida la secuencia de prerrequisitos" breadcrumbs={[{ label: 'Inicio', href: '/dashboard' }, { label: 'Campus y Planes', href: '/estructura-academica' }, { label: 'Organizar Pensum', active: true }]} actions={<button disabled={!plan || saving || issues.length > 0} onClick={save} className="flex items-center gap-2 rounded-lg bg-[#800020] px-5 py-2.5 text-xs font-bold text-white disabled:cursor-not-allowed disabled:opacity-50"><Save className="h-4 w-4" />{saving ? 'Guardando...' : 'Guardar distribución'}</button>} />
    <section className="grid gap-4 rounded-xl border bg-white p-5 shadow-xs lg:grid-cols-3"><label className="text-xs font-bold">Carrera<select value={careerId} onChange={(event) => setCareerId(event.target.value)} className="mt-1 w-full rounded-lg border px-3 py-2.5 font-normal">{data.careers.map((career) => <option key={career.code} value={career.code}>{career.name}</option>)}</select></label><label className="text-xs font-bold">Versión del pensum<select value={planId} onChange={(event) => setPlanId(event.target.value)} className="mt-1 w-full rounded-lg border px-3 py-2.5 font-normal">{careerPlans.map((item) => <option key={item.id} value={item.id}>{item.code} · {item.name} ({item.status})</option>)}</select></label><label className="text-xs font-bold">Cantidad de semestres<input type="number" min="1" max="12" value={duration} onChange={(event) => changeDuration(Number(event.target.value))} className="mt-1 w-full rounded-lg border px-3 py-2.5 font-normal" /></label></section>
    {plan && <><div className="grid gap-3 sm:grid-cols-3"><div className="rounded-xl border bg-white p-4"><p className="text-[10px] uppercase text-[#64748B]">Cursos del pensum</p><p className="text-2xl font-black">{plan.courses.length}</p></div><div className="rounded-xl border bg-white p-4"><p className="text-[10px] uppercase text-[#64748B]">Créditos totales</p><p className="text-2xl font-black">{plan.courses.reduce((sum, course) => sum + course.credits, 0)}</p></div><div className={`rounded-xl border p-4 ${issues.length ? 'border-red-200 bg-red-50' : 'border-green-200 bg-green-50'}`}><p className="text-[10px] uppercase text-[#64748B]">Validación</p><p className={`text-sm font-black ${issues.length ? 'text-red-700' : 'text-green-700'}`}>{issues.length ? `${issues.length} conflicto(s)` : 'Secuencia correcta'}</p></div></div>
      {issues.length > 0 && <section className="rounded-xl border border-red-200 bg-red-50 p-4"><div className="mb-2 flex items-center gap-2 text-red-800"><AlertTriangle className="h-5 w-5" /><h2 className="text-sm font-bold">Prerrequisitos en orden incorrecto</h2></div><div className="flex flex-wrap gap-2">{issues.map((issue) => <span key={`${issue.courseCode}-${issue.prerequisiteCode}`} className="rounded-full border border-red-200 bg-white px-3 py-1 text-[10px] font-bold text-red-700">{issue.message}</span>)}</div></section>}
      <div className="rounded-xl border bg-[#F8FAFC] p-4"><div className="grid grid-cols-1 gap-4 md:grid-cols-2 xl:grid-cols-4">{Array.from({ length: duration }, (_, index) => index + 1).map((semester) => { const courses = plan.courses.filter((course) => assignments[course.code] === semester); const credits = courses.reduce((sum, course) => sum + course.credits, 0); return <section key={semester} onDragOver={(event) => event.preventDefault()} onDrop={(event) => moveCourse(event.dataTransfer.getData('text/course') || dragging || '', semester)} className={`min-w-0 self-start overflow-hidden rounded-xl border bg-white shadow-xs ${dragging ? 'border-dashed border-[#800020]/50' : ''}`}><header className="bg-[#1E293B] px-4 py-3 text-white"><div className="flex items-center justify-between"><div className="flex items-center gap-2"><BookOpenCheck className="h-4 w-4" /><h2 className="text-sm font-bold">Semestre {semester}</h2></div><span className="text-[10px] text-white/70">{credits} CR</span></div><p className="mt-1 text-[9px] text-white/60">{courses.length} cursos</p></header><div className="min-h-28 space-y-2 p-2">{courses.map((course) => { const hasIssue = issues.some((issue) => issue.courseCode === course.code || issue.prerequisiteCode === course.code); return <article key={course.code} draggable onDragStart={(event) => { event.dataTransfer.setData('text/course', course.code); event.dataTransfer.effectAllowed = 'move'; setDragging(course.code); }} onDragEnd={() => setDragging(null)} className={`cursor-grab rounded-lg border p-3 active:cursor-grabbing ${hasIssue ? 'border-red-300 bg-red-50' : 'bg-white hover:border-[#800020]/40 hover:shadow-sm'}`}><div className="flex items-start gap-2"><GripVertical className="mt-0.5 h-4 w-4 shrink-0 text-[#94A3B8]" /><div className="min-w-0 flex-1"><div className="flex justify-between gap-2"><p className="text-[10px] font-extrabold text-[#800020]">{course.code}</p><span className="text-[9px] font-bold text-[#64748B]">{course.credits} CR</span></div><p className="mt-0.5 text-xs font-bold leading-snug">{course.name}</p>{course.prerequisites.length > 0 && <p className="mt-2 text-[9px] text-[#64748B]">Requiere: {course.prerequisites.map((item) => item.code).join(', ')}</p>}</div></div></article>; })}{courses.length === 0 && <div className="flex min-h-24 items-center justify-center rounded-lg border border-dashed text-[10px] text-[#94A3B8]">Arrastra cursos aquí</div>}</div></section>; })}</div></div>
      <p className="text-center text-[10px] text-[#64748B]">Arrastra cada tarjeta a otro semestre. No podrás guardar si un prerrequisito queda en el mismo semestre o después del curso que lo requiere.</p></>}
  </div></RoleGuard>;
};
