import React, { useCallback, useEffect, useState } from 'react';
import { BookOpenCheck, CheckCircle2, CircleDashed, Clock3, GraduationCap, LockKeyhole } from 'lucide-react';
import { PageHeader } from '../components/common/PageHeader';
import { RoleGuard } from '../components/common/RoleGuard';
import { useApp } from '../context/AppContext';
import { apiGet } from '../services/api';
import { StudentPicker } from '../components/common/StudentPicker';

interface MapCourse { code: string; name: string; credits: number; semester: number; status: 'APROBADO' | 'EN_CURSO' | 'DISPONIBLE' | 'BLOQUEADO'; prerequisites: { code: string; name: string; completed: boolean }[]; missingPrerequisites: { code: string; name: string }[]; unlocks: { code: string; name: string; semester: number }[]; }
interface MapData { student: { carnet: string; name: string; careerName: string; campusName: string; planCode: string; planName: string; planVersion: string }; curriculum: { totalCourses: number; totalCredits: number; semesters: number; approvedCourses: number; approvedCredits: number; progress: number }; courses: MapCourse[]; graduationRequirements: { code: string; label: string; completed: boolean; detail: string }[]; }
const styles = { APROBADO: 'border-green-200 bg-green-50 text-green-800', EN_CURSO: 'border-blue-200 bg-blue-50 text-blue-800', DISPONIBLE: 'border-amber-200 bg-amber-50 text-amber-800', BLOQUEADO: 'border-slate-200 bg-slate-50 text-slate-500' };
const icons = { APROBADO: CheckCircle2, EN_CURSO: Clock3, DISPONIBLE: CircleDashed, BLOQUEADO: LockKeyhole };

export const CurriculumMapPage: React.FC = () => {
  const { currentUser, students, showToast } = useApp();
  const [studentCarnet, setStudentCarnet] = useState(currentUser.role === 'ESTUDIANTE' ? currentUser.carnetOrCode || '' : students[0]?.carnet || '');
  const [data, setData] = useState<MapData | null>(null);
  const [loading, setLoading] = useState(true);
  const load = useCallback(async () => { if (!studentCarnet) return; setLoading(true); try { const query = ['ADMIN', 'REGISTRO'].includes(currentUser.role) ? `?studentCarnet=${encodeURIComponent(studentCarnet)}` : ''; setData(await apiGet<MapData>(`/api/curriculum-map${query}`)); } catch (error) { showToast(error instanceof Error ? error.message : 'No se pudo cargar la malla', 'error'); } finally { setLoading(false); } }, [currentUser.role, studentCarnet]);
  useEffect(() => { load(); }, [load]);
  return <RoleGuard allowedRoles={['ADMIN', 'REGISTRO', 'ESTUDIANTE']}><div className="space-y-6"><PageHeader title="Malla Estudiantil" description="Avance por semestre, créditos y prerrequisitos del pensum asignado" breadcrumbs={[{ label: 'Inicio', href: '/dashboard' }, { label: 'Malla Estudiantil', active: true }]} />
    {['ADMIN', 'REGISTRO'].includes(currentUser.role) && <div className="rounded-xl border border-[#E2E8F0] bg-white p-5"><StudentPicker students={students} value={studentCarnet} onChange={setStudentCarnet} label="Estudiante" /></div>}
    {loading ? <div className="rounded-xl bg-white p-10 text-center text-sm text-[#64748B]">Cargando malla...</div> : data && <><div className="rounded-xl border border-[#800020]/20 bg-white p-6 shadow-xs"><div className="flex flex-col justify-between gap-4 md:flex-row md:items-center"><div><p className="text-xs font-bold uppercase text-[#800020]">{data.student.carnet}</p><h2 className="text-xl font-extrabold">{data.student.name}</h2><p className="text-sm text-[#64748B]">{data.student.careerName}</p><div className="mt-2 flex flex-wrap gap-2 text-[10px] font-bold"><span className="rounded-full bg-slate-100 px-3 py-1">{data.student.campusName}</span><span className="rounded-full bg-[#800020]/10 px-3 py-1 text-[#800020]">Pensum {data.student.planVersion} · {data.student.planCode}</span></div></div><div className="grid grid-cols-3 gap-5 text-center"><div><p className="text-xl font-extrabold">{data.curriculum.approvedCourses}/{data.curriculum.totalCourses}</p><p className="text-[10px] uppercase text-[#64748B]">Cursos</p></div><div><p className="text-xl font-extrabold">{data.curriculum.approvedCredits}/{data.curriculum.totalCredits}</p><p className="text-[10px] uppercase text-[#64748B]">Créditos</p></div><div><p className="text-xl font-extrabold text-[#800020]">{data.curriculum.progress}%</p><p className="text-[10px] uppercase text-[#64748B]">Avance</p></div></div></div><div className="mt-5 h-3 overflow-hidden rounded-full bg-[#E2E8F0]"><div className="h-full rounded-full bg-[#800020] transition-all" style={{ width: `${data.curriculum.progress}%` }} /></div><div className="mt-4 flex flex-wrap gap-3">{Object.entries(styles).map(([status, style]) => <span key={status} className={`rounded-full border px-3 py-1 text-[10px] font-bold ${style}`}>{status.replace('_', ' ')}</span>)}</div></div>
      <div className="grid gap-5 xl:grid-cols-2">
        {Array.from({ length: data.curriculum.semesters }, (_, index) => index + 1).map((semester) => {
          const semesterCourses = data.courses.filter((course) => course.semester === semester);
          const semesterCredits = semesterCourses.reduce((sum, course) => sum + course.credits, 0);
          return <section key={semester} className="overflow-hidden rounded-xl border border-[#E2E8F0] bg-white shadow-xs">
            <div className="flex items-center justify-between bg-[#1E293B] px-5 py-3 text-white"><div className="flex items-center gap-2"><BookOpenCheck className="h-4 w-4" /><h3 className="text-sm font-bold">{semester}° Semestre</h3></div><span className="text-xs font-semibold">{semesterCourses.length} cursos · {semesterCredits} créditos</span></div>
            <div className="divide-y divide-[#E2E8F0]">{semesterCourses.length === 0 ? <p className="p-6 text-center text-xs text-[#64748B]">No hay cursos registrados en este semestre.</p> : semesterCourses.map((course) => {
              const Icon = icons[course.status];
              return <div key={course.code} className="p-3"><div className={`flex items-start gap-3 rounded-lg border p-3 ${styles[course.status]}`}><Icon className="mt-0.5 h-4 w-4 shrink-0" /><div className="min-w-0 flex-1"><div className="flex justify-between gap-2"><p className="text-xs font-bold">{course.code} · {course.name}</p><span className="shrink-0 text-xs font-extrabold">{course.credits} CR</span></div><div className="mt-2 border-t border-current/10 pt-2"><p className="text-[9px] font-extrabold uppercase tracking-wide opacity-70">Debe aprobar antes</p>{course.prerequisites.length === 0 ? <p className="mt-1 text-[10px]">No requiere prerrequisitos</p> : <div className="mt-1 flex flex-wrap gap-1.5">{course.prerequisites.map((item) => <span key={item.code} title={item.name} className={`rounded-full border px-2 py-1 text-[9px] font-bold ${item.completed ? 'border-green-300 bg-green-100 text-green-800' : 'border-slate-300 bg-white/70 text-slate-700'}`}>{item.completed ? '✓ ' : '○ '}{item.code} · {item.name}</span>)}</div>}</div>{course.unlocks.length > 0 && <div className="mt-2 border-t border-current/10 pt-2"><p className="text-[9px] font-extrabold uppercase tracking-wide opacity-70">Al aprobarlo habilita</p><div className="mt-1 flex flex-wrap gap-1.5">{course.unlocks.map((item) => <span key={item.code} title={item.name} className="rounded-full border border-blue-200 bg-blue-50 px-2 py-1 text-[9px] font-bold text-blue-800">→ {item.code} · {item.name} ({item.semester}°)</span>)}</div></div>}</div></div></div>;
            })}</div>
          </section>;
        })}
      </div>
      <section className="rounded-xl border border-[#E2E8F0] bg-white p-5 shadow-xs"><div className="mb-4 flex items-center gap-2"><GraduationCap className="h-5 w-5 text-[#800020]" /><h3 className="text-sm font-bold">Requisitos de graduación</h3></div><div className="grid gap-3 md:grid-cols-2 xl:grid-cols-5">{data.graduationRequirements.map((item) => <div key={item.code} className={`rounded-lg border p-4 ${item.completed ? 'border-green-200 bg-green-50' : 'border-slate-200 bg-slate-50'}`}>{item.completed ? <CheckCircle2 className="mb-2 h-5 w-5 text-green-600" /> : <CircleDashed className="mb-2 h-5 w-5 text-slate-500" />}<p className="text-xs font-bold">{item.label}</p><p className="mt-1 text-[10px] text-[#64748B]">{item.detail}</p></div>)}</div></section></>}
  </div></RoleGuard>;
};
