import React, { useCallback, useEffect, useState } from 'react';
import { CheckCircle2, Eye, FileCheck2, FileUp, FolderOpen, ShieldCheck, XCircle } from 'lucide-react';
import { PageHeader } from '../components/common/PageHeader';
import { RoleGuard } from '../components/common/RoleGuard';
import { useApp } from '../context/AppContext';
import { StudentPicker } from '../components/common/StudentPicker';

interface DocumentRecord { id: string; type: string; fileName: string; mimeType: string; status: string; reviewNote?: string; reviewedBy?: string; createdAt: string; }
interface Requirement { type: string; label: string; document: DocumentRecord | null; }
export const EnrollmentDocumentsPage: React.FC = () => {
  const { currentUser, students, showToast } = useApp();
  const [studentCarnet, setStudentCarnet] = useState(currentUser.role === 'ESTUDIANTE' ? currentUser.carnetOrCode || '' : students[0]?.carnet || '');
  const [requirements, setRequirements] = useState<Requirement[]>([]);
  const [summary, setSummary] = useState({ total: 5, uploaded: 0, approved: 0, complete: false });
  const [loading, setLoading] = useState(true);
  const [uploading, setUploading] = useState('');
  const [notes, setNotes] = useState<Record<string, string>>({});
  const load = useCallback(async () => { if (!studentCarnet) return; setLoading(true); try { const query = currentUser.role === 'ADMIN' ? `?studentCarnet=${encodeURIComponent(studentCarnet)}` : ''; const response = await fetch(`/api/enrollment-documents${query}`); const result = await response.json(); if (!response.ok) throw new Error(result.message); setRequirements(result.requirements); setSummary(result.summary); } catch (error) { showToast(error instanceof Error ? error.message : 'No se pudo cargar el expediente', 'error'); } finally { setLoading(false); } }, [studentCarnet, currentUser.role]);
  useEffect(() => { load(); }, [load]);
  const upload = (type: string, file?: File) => { if (!file) return; if (file.size > 3 * 1024 * 1024) return showToast('El archivo no puede superar 3 MB', 'error'); setUploading(type); const reader = new FileReader(); reader.onload = async () => { const response = await fetch('/api/enrollment-documents', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ type, fileName: file.name, dataUrl: reader.result }) }); const result = await response.json(); setUploading(''); if (!response.ok) return showToast(result.message, 'error'); showToast('Documento cargado para revisión', 'success'); await load(); }; reader.onerror = () => { setUploading(''); showToast('No se pudo leer el archivo', 'error'); }; reader.readAsDataURL(file); };
  const review = async (id: string, status: string) => { const response = await fetch(`/api/enrollment-documents/${id}/review`, { method: 'PATCH', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ status, reviewNote: notes[id] || '' }) }); const result = await response.json(); if (!response.ok) return showToast(result.message, 'error'); showToast(`Documento ${status.toLowerCase()}`, 'success'); await load(); };
  const statusClass = (status: string) => status === 'APROBADO' ? 'bg-green-100 text-green-700' : status === 'RECHAZADO' ? 'bg-red-100 text-red-700' : 'bg-amber-100 text-amber-700';
  return <RoleGuard allowedRoles={['ADMIN', 'ESTUDIANTE']}><div className="space-y-6"><PageHeader title="Expediente de Inscripción" description="Carga, validación y seguimiento de documentos requeridos" breadcrumbs={[{ label: 'Inicio', href: '/dashboard' }, { label: 'Expediente', active: true }]} />
    {currentUser.role === 'ADMIN' && <div className="rounded-xl border border-[#E2E8F0] bg-white p-5"><StudentPicker students={students} value={studentCarnet} onChange={setStudentCarnet} label="Expediente del estudiante" /></div>}
    <div className="grid gap-4 sm:grid-cols-3"><div className="rounded-xl border bg-white p-5"><FolderOpen className="h-5 w-5 text-[#800020]" /><p className="mt-3 text-xs text-[#64748B]">Documentos cargados</p><p className="text-2xl font-extrabold">{summary.uploaded}/{summary.total}</p></div><div className="rounded-xl border bg-white p-5"><FileCheck2 className="h-5 w-5 text-[#2F855A]" /><p className="mt-3 text-xs text-[#64748B]">Documentos aprobados</p><p className="text-2xl font-extrabold">{summary.approved}/{summary.total}</p></div><div className={`rounded-xl border p-5 ${summary.complete ? 'border-green-200 bg-green-50' : 'bg-white'}`}><ShieldCheck className={`h-5 w-5 ${summary.complete ? 'text-green-600' : 'text-[#64748B]'}`} /><p className="mt-3 text-xs text-[#64748B]">Estado del expediente</p><p className="text-lg font-extrabold">{summary.complete ? 'COMPLETO' : 'INCOMPLETO'}</p></div></div>
    {loading ? <div className="rounded-xl bg-white p-8 text-center text-sm text-[#64748B]">Cargando expediente...</div> : <div className="grid gap-4">{requirements.map((requirement) => <div key={requirement.type} className="rounded-xl border border-[#E2E8F0] bg-white p-5 shadow-xs"><div className="flex flex-col justify-between gap-4 lg:flex-row lg:items-center"><div className="flex items-start gap-3"><div className="rounded-lg bg-[#800020]/10 p-2.5"><FileUp className="h-5 w-5 text-[#800020]" /></div><div><div className="flex flex-wrap items-center gap-2"><h3 className="text-sm font-bold">{requirement.label}</h3>{requirement.document ? <span className={`rounded-full px-2 py-1 text-[10px] font-bold ${statusClass(requirement.document.status)}`}>{requirement.document.status}</span> : <span className="rounded-full bg-slate-100 px-2 py-1 text-[10px] font-bold text-slate-600">FALTANTE</span>}</div>{requirement.document && <><p className="mt-1 text-xs text-[#64748B]">{requirement.document.fileName} · cargado {new Date(requirement.document.createdAt).toLocaleDateString('es-GT')}</p>{requirement.document.reviewNote && <p className="mt-2 text-xs text-red-700">Observación: {requirement.document.reviewNote}</p>}</>}</div></div><div className="flex flex-wrap items-center justify-end gap-2">{requirement.document && <a target="_blank" rel="noreferrer" href={`/api/enrollment-documents/${requirement.document.id}/file`} className="rounded-lg border px-3 py-2 text-xs font-bold"><Eye className="mr-1 inline h-4 w-4" />Ver</a>}{currentUser.role === 'ESTUDIANTE' && requirement.document?.status !== 'APROBADO' && <label className="cursor-pointer rounded-lg bg-[#800020] px-3 py-2 text-xs font-bold text-white"><FileUp className="mr-1 inline h-4 w-4" />{uploading === requirement.type ? 'Cargando...' : requirement.document ? 'Reemplazar' : 'Cargar'}<input disabled={Boolean(uploading)} type="file" accept="application/pdf,image/png,image/jpeg" className="hidden" onChange={(e) => upload(requirement.type, e.target.files?.[0])} /></label>}{currentUser.role === 'ADMIN' && requirement.document && requirement.document.status !== 'APROBADO' && <><input value={notes[requirement.document.id] || ''} onChange={(e) => setNotes({ ...notes, [requirement.document!.id]: e.target.value })} placeholder="Observación si se rechaza" className="rounded-lg border px-3 py-2 text-xs" /><button onClick={() => review(requirement.document!.id, 'APROBADO')} className="rounded-lg bg-green-600 px-3 py-2 text-xs font-bold text-white"><CheckCircle2 className="mr-1 inline h-4 w-4" />Aprobar</button><button onClick={() => review(requirement.document!.id, 'RECHAZADO')} className="rounded-lg bg-red-600 px-3 py-2 text-xs font-bold text-white"><XCircle className="mr-1 inline h-4 w-4" />Rechazar</button></>}</div></div></div>)}</div>}
  </div></RoleGuard>;
};
