import React, { useCallback, useEffect, useMemo, useState } from 'react';
import { BookOpen, BookPlus, CheckCircle2, Clock3, CopyPlus, Edit2, Library, RotateCcw, Search, UserPlus, X } from 'lucide-react';
import { useApp } from '../context/AppContext';
import { PageHeader } from '../components/common/PageHeader';
import { RoleGuard } from '../components/common/RoleGuard';
import { Pagination } from '../components/common/Pagination';
import { QrCode } from '../components/common/QrCode';
import { QrScanner } from '../components/common/QrScanner';
import { PasswordInput } from '../components/common/PasswordInput';

interface BookRecord { id: string; isbn?: string; title: string; author: string; category: string; available: number; totalCopies: number; copies: { id: string; barcode: string; location: string; status: string; condition: string }[]; }
interface LoanRecord { id: string; dueAt: string; returnedAt?: string; status: string; renewalCount: number; borrowerId: string; borrowerName: string; borrowerCode?: string; suspendedUntil?: string; suspensionReason?: string; barcode: string; bookTitle: string; }
interface ReservationRecord { id: string; status: string; expiresAt: string; assignedCopyId?: string; readyAt?: string; user: { name: string; carnetOrCode?: string; email: string }; book: { title: string }; }

export const LibraryPage: React.FC = () => {
  const { currentUser, showToast } = useApp(); const staff = currentUser.role === 'ADMIN' || currentUser.role === 'BIBLIOTECA';
  const [books, setBooks] = useState<BookRecord[]>([]), [loans, setLoans] = useState<LoanRecord[]>([]), [reservations, setReservations] = useState<ReservationRecord[]>([]), [metrics, setMetrics] = useState<any>({popularBooks:[],overdue:0,damagedCopies:0}), [search, setSearch] = useState(''), [panel, setPanel] = useState<'BOOK' | 'LOAN' | 'STAFF' | 'INCIDENT' | null>(null);
  const [bookForm, setBookForm] = useState({ title: '', author: '', isbn: '', category: '', barcode: '', location: 'Biblioteca Central' }); const [loanForm, setLoanForm] = useState({ borrowerCode: '', barcode: '', days: '7' }); const [staffForm, setStaffForm] = useState({ name: '', email: '', code: '' }); const [credential, setCredential] = useState<{ email: string; password: string } | null>(null);
  const [editBook, setEditBook] = useState<BookRecord | null>(null);
  const [editBookForm, setEditBookForm] = useState({ title: '', author: '', category: '', isbn: '', publisher: '' });
  const [editCopy, setEditCopy] = useState<{ id: string; bookTitle: string; status: string; condition: string; location: string } | null>(null);
  const [addCopyForm, setAddCopyForm] = useState({ barcode: '', location: 'Biblioteca Central' });
  const [addCopyBookId, setAddCopyBookId] = useState<string | null>(null);
  const [scanTarget, setScanTarget] = useState<'BORROWER' | 'COPY' | null>(null);
  const [selectedLoan, setSelectedLoan] = useState<LoanRecord|null>(null), [incident, setIncident] = useState({type:'DANADO',notes:'',suspensionDays:'15'});
  const load = useCallback(async () => { const response = await fetch('/api/library'); const result = await response.json(); if (!response.ok) return showToast(result.message, 'error'); setBooks(result.books); setLoans(result.loans); setReservations(result.reservations); setMetrics(result.metrics||{popularBooks:[],overdue:0,damagedCopies:0}); }, [showToast]); useEffect(() => { load(); }, [load]);
  const [bookPage, setBookPage] = useState(1);
  const [bookPageSize, setBookPageSize] = useState(20);
  const filtered = useMemo(() => books.filter((book) => `${book.title} ${book.author} ${book.category} ${book.isbn || ''}`.toLowerCase().includes(search.toLowerCase())), [books, search]);
  const paginatedBooks = filtered.slice((bookPage - 1) * bookPageSize, bookPage * bookPageSize);
  const post = async (url: string, body: object, method = 'POST') => { const response = await fetch(url, { method, headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(body) }); const result = await response.json(); if (!response.ok) { showToast(result.message, 'error'); return null; } return result; };
  const createBook = async (e: React.FormEvent) => { e.preventDefault(); if (!(await post('/api/library/books', bookForm))) return; showToast('Libro y primer ejemplar registrados', 'success'); setPanel(null); setBookForm({ title: '', author: '', isbn: '', category: '', barcode: '', location: 'Biblioteca Central' }); await load(); };
  const createLoan = async (e: React.FormEvent) => { e.preventDefault(); if (!(await post('/api/library/loans', { ...loanForm, days: Number(loanForm.days) }))) return; showToast('Préstamo registrado', 'success'); setPanel(null); setLoanForm({ borrowerCode: '', barcode: '', days: '7' }); await load(); };
  const createStaff = async (e: React.FormEvent) => { e.preventDefault(); const result = await post('/api/library/staff', staffForm); if (!result) return; setCredential({ email: result.user.email, password: result.temporaryPassword }); showToast('Usuario de biblioteca creado', 'success'); setPanel(null); };
  const action = async (url: string, message: string) => { if (!(await post(url, {}))) return; showToast(message, 'success'); await load(); };
  const saveIncident = async (e:React.FormEvent) => { e.preventDefault();if(!selectedLoan||!(await post(`/api/library/loans/${selectedLoan.id}/incident`,{...incident,suspensionDays:Number(incident.suspensionDays)})))return;showToast('Incidencia registrada y usuario notificado','success');setPanel(null);setSelectedLoan(null);setIncident({type:'DANADO',notes:'',suspensionDays:'15'});await load(); };
  const saveEditBook = async (e: React.FormEvent) => { e.preventDefault(); if (!editBook) return; if (!(await post(`/api/library/books/${editBook.id}`, editBookForm, 'PATCH'))) return; showToast('Libro actualizado', 'success'); setEditBook(null); await load(); };
  const saveCopyStatus = async (e: React.FormEvent) => { e.preventDefault(); if (!editCopy) return; if (!(await post(`/api/library/copies/${editCopy.id}/status`, { status: editCopy.status, condition: editCopy.condition, location: editCopy.location }, 'PATCH'))) return; showToast('Ejemplar actualizado', 'success'); setEditCopy(null); await load(); };
  const addCopy = async (e: React.FormEvent) => { e.preventDefault(); if (!addCopyBookId) return; if (!(await post(`/api/library/books/${addCopyBookId}/copies`, addCopyForm))) return; showToast('Ejemplar agregado', 'success'); setAddCopyBookId(null); setAddCopyForm({ barcode: '', location: 'Biblioteca Central' }); await load(); };
  return <RoleGuard allowedRoles={['ADMIN', 'BIBLIOTECA', 'ESTUDIANTE', 'DOCENTE']}><div className="space-y-6"><PageHeader title="Biblioteca USPG" description="Catálogo, ejemplares, préstamos, devoluciones y reservas" breadcrumbs={[{ label: 'Inicio', href: '/dashboard' }, { label: 'Biblioteca', active: true }]} actions={staff ? <div className="flex flex-wrap gap-2"><button onClick={() => setPanel('LOAN')} className="flex items-center gap-2 rounded-lg bg-[#800020] px-4 py-2 text-xs font-bold text-white"><BookOpen className="h-4 w-4" />Nuevo préstamo</button><button onClick={() => setPanel('BOOK')} className="flex items-center gap-2 rounded-lg border bg-white px-4 py-2 text-xs font-bold"><BookPlus className="h-4 w-4" />Registrar libro</button>{currentUser.role === 'ADMIN' && <button onClick={() => setPanel('STAFF')} className="flex items-center gap-2 rounded-lg border bg-white px-4 py-2 text-xs font-bold"><UserPlus className="h-4 w-4" />Usuario biblioteca</button>}</div> : undefined} />
    {credential && <div className="rounded-xl border border-green-200 bg-green-50 p-4 text-xs"><p className="font-bold text-green-800">Credencial temporal generada</p><p className="mt-2">Correo: <strong>{credential.email}</strong></p><label className="mt-2 block font-bold text-green-800">Contraseña temporal</label><PasswordInput readOnly value={credential.password} aria-label="Contraseña temporal generada" className="mt-1 w-full rounded-lg border border-green-200 bg-white px-3 py-2 font-mono font-bold" /><p className="mt-2 text-green-700">Guárdala ahora; se solicitará cambiarla al iniciar sesión.</p></div>}
    {staff && <div className="grid gap-3 sm:grid-cols-3">{[['Solicitudes pendientes',reservations.filter((item)=>['ACTIVA','SOLICITADA'].includes(item.status)).length,'text-blue-700 bg-blue-50'],['Listas para recoger',reservations.filter((item)=>item.status==='LISTA').length,'text-green-700 bg-green-50'],['Préstamos vencidos',loans.filter((item)=>item.status==='VENCIDO').length,'text-red-700 bg-red-50']].map(([label,value,style])=><div key={label as string} className={`rounded-xl border p-4 ${style}`}><Clock3 className="mb-2 h-4 w-4"/><p className="text-[10px] font-bold uppercase">{label}</p><p className="text-2xl font-black">{value}</p></div>)}</div>}
    {staff && <section className="rounded-xl border bg-white p-5"><div className="flex flex-wrap items-start justify-between gap-4"><div><h2 className="font-bold">Uso de la colección</h2><p className="text-xs text-[#64748B]">Libros más solicitados según el historial</p></div><div className="flex gap-4 text-xs"><span><strong className="text-red-700">{metrics.overdue}</strong> vencidos</span><span><strong className="text-amber-700">{metrics.damagedCopies}</strong> fuera de circulación</span></div></div><div className="mt-4 grid gap-2 sm:grid-cols-2 lg:grid-cols-5">{metrics.popularBooks.map((item:any,index:number)=><div key={item.title} className="rounded-lg bg-[#F8FAFC] p-3"><p className="text-[10px] font-bold text-[#800020]">#{index+1}</p><p className="line-clamp-2 text-xs font-bold">{item.title}</p><p className="mt-1 text-[10px] text-[#64748B]">{item.count} préstamos</p></div>)}</div></section>}
    {!staff && <section className="flex flex-col items-center gap-4 rounded-xl border border-[#800020]/20 bg-white p-5 text-center sm:flex-row sm:text-left"><QrCode value={currentUser.carnetOrCode || currentUser.email} label="Identificación de Biblioteca" size={130}/><div><h2 className="font-bold">Mi identificación digital</h2><p className="mt-1 text-xs text-[#64748B]">Presenta este QR al retirar un libro. Biblioteca escanea tu identidad y el ejemplar para confirmar el préstamo.</p><p className="mt-2 font-mono text-sm font-bold text-[#800020]">{currentUser.carnetOrCode || currentUser.email}</p></div></section>}
    {panel === 'BOOK' && <form onSubmit={createBook} className="grid gap-3 rounded-xl border bg-white p-5 md:grid-cols-3"><h3 className="font-bold md:col-span-3">Registrar libro y ejemplar inicial</h3><input required value={bookForm.title} onChange={(e) => setBookForm({ ...bookForm, title: e.target.value })} placeholder="Título" className="rounded-lg border px-3 py-2 text-sm"/><input required value={bookForm.author} onChange={(e) => setBookForm({ ...bookForm, author: e.target.value })} placeholder="Autor" className="rounded-lg border px-3 py-2 text-sm"/><input required value={bookForm.category} onChange={(e) => setBookForm({ ...bookForm, category: e.target.value })} placeholder="Categoría" className="rounded-lg border px-3 py-2 text-sm"/><input value={bookForm.isbn} onChange={(e) => setBookForm({ ...bookForm, isbn: e.target.value })} placeholder="ISBN opcional" className="rounded-lg border px-3 py-2 text-sm"/><input required value={bookForm.barcode} onChange={(e) => setBookForm({ ...bookForm, barcode: e.target.value })} placeholder="Código de barras / QR" className="rounded-lg border px-3 py-2 text-sm"/><input value={bookForm.location} onChange={(e) => setBookForm({ ...bookForm, location: e.target.value })} placeholder="Ubicación" className="rounded-lg border px-3 py-2 text-sm"/><div className="md:col-span-3 flex justify-end gap-2"><button type="button" onClick={() => setPanel(null)} className="rounded-lg border px-4 py-2 text-xs">Cancelar</button><button className="rounded-lg bg-[#800020] px-4 py-2 text-xs font-bold text-white">Guardar</button></div></form>}
    {panel === 'LOAN' && <form onSubmit={createLoan} className="grid gap-3 rounded-xl border bg-white p-5 md:grid-cols-6"><h3 className="font-bold md:col-span-6">Confirmar entrega y préstamo</h3><input required value={loanForm.borrowerCode} onChange={(e) => setLoanForm({ ...loanForm, borrowerCode: e.target.value })} placeholder="Carné, código o correo" className="rounded-lg border px-3 py-2 text-sm"/><button type="button" onClick={()=>setScanTarget('BORROWER')} className="rounded-lg border border-[#800020] px-3 py-2 text-xs font-bold text-[#800020]">Escanear alumno</button><input required value={loanForm.barcode} onChange={(e) => setLoanForm({ ...loanForm, barcode: e.target.value })} placeholder="Código del ejemplar" className="rounded-lg border px-3 py-2 text-sm"/><button type="button" onClick={()=>setScanTarget('COPY')} className="rounded-lg border border-[#800020] px-3 py-2 text-xs font-bold text-[#800020]">Escanear ejemplar</button><input required min="1" max="30" type="number" value={loanForm.days} onChange={(e) => setLoanForm({ ...loanForm, days: e.target.value })} className="rounded-lg border px-3 py-2 text-sm"/><button className="rounded-lg bg-[#800020] px-4 py-2 text-xs font-bold text-white">Confirmar préstamo</button></form>}
    {panel === 'STAFF' && <form onSubmit={createStaff} className="grid gap-3 rounded-xl border bg-white p-5 md:grid-cols-4"><h3 className="font-bold md:col-span-4">Crear acceso exclusivo de Biblioteca</h3><input required value={staffForm.name} onChange={(e) => setStaffForm({ ...staffForm, name: e.target.value })} placeholder="Nombre completo" className="rounded-lg border px-3 py-2 text-sm"/><input required type="email" value={staffForm.email} onChange={(e) => setStaffForm({ ...staffForm, email: e.target.value })} placeholder="usuario@biblioteca.uspg.edu.gt" className="rounded-lg border px-3 py-2 text-sm"/><input required value={staffForm.code} onChange={(e) => setStaffForm({ ...staffForm, code: e.target.value })} placeholder="Código de empleado" className="rounded-lg border px-3 py-2 text-sm"/><button className="rounded-lg bg-[#1E293B] px-4 py-2 text-xs font-bold text-white">Crear usuario</button></form>}
    {panel === 'INCIDENT' && selectedLoan && <form onSubmit={saveIncident} className="grid gap-3 rounded-xl border border-red-200 bg-white p-5 md:grid-cols-4"><h3 className="font-bold text-red-700 md:col-span-4">Incidencia · {selectedLoan.bookTitle}</h3><select value={incident.type} onChange={(e)=>setIncident({...incident,type:e.target.value})} className="rounded-lg border px-3 py-2 text-sm"><option value="DANADO">Ejemplar dañado</option><option value="PERDIDO">Ejemplar perdido</option></select><input required minLength={5} value={incident.notes} onChange={(e)=>setIncident({...incident,notes:e.target.value})} placeholder="Detalle de la incidencia" className="rounded-lg border px-3 py-2 text-sm"/><label className="text-[10px] font-bold">Días de suspensión<input min="0" max="365" type="number" value={incident.suspensionDays} onChange={(e)=>setIncident({...incident,suspensionDays:e.target.value})} className="mt-1 w-full rounded-lg border px-3 py-2 text-sm font-normal"/></label><button className="self-end rounded-lg bg-red-700 px-3 py-2 text-xs font-bold text-white">Registrar incidencia</button></form>}
    <div className="relative"><Search className="absolute left-3 top-3 h-4 w-4 text-[#64748B]"/><input value={search} onChange={(e) => setSearch(e.target.value)} placeholder="Buscar por título, autor, ISBN o categoría" className="w-full rounded-xl border bg-white py-2.5 pl-10 pr-3 text-sm"/></div>
    {editBook && <form onSubmit={saveEditBook} className="grid gap-3 rounded-xl border bg-white p-5 md:grid-cols-3"><h3 className="font-bold md:col-span-3">Editar libro · {editBook.title}</h3><input required value={editBookForm.title} onChange={(e) => setEditBookForm({ ...editBookForm, title: e.target.value })} placeholder="Título" className="rounded-lg border px-3 py-2 text-sm"/><input required value={editBookForm.author} onChange={(e) => setEditBookForm({ ...editBookForm, author: e.target.value })} placeholder="Autor" className="rounded-lg border px-3 py-2 text-sm"/><input required value={editBookForm.category} onChange={(e) => setEditBookForm({ ...editBookForm, category: e.target.value })} placeholder="Categoría" className="rounded-lg border px-3 py-2 text-sm"/><input value={editBookForm.isbn} onChange={(e) => setEditBookForm({ ...editBookForm, isbn: e.target.value })} placeholder="ISBN opcional" className="rounded-lg border px-3 py-2 text-sm"/><input value={editBookForm.publisher} onChange={(e) => setEditBookForm({ ...editBookForm, publisher: e.target.value })} placeholder="Editorial" className="rounded-lg border px-3 py-2 text-sm"/><div className="md:col-span-3 flex justify-end gap-2"><button type="button" onClick={() => setEditBook(null)} className="rounded-lg border px-4 py-2 text-xs">Cancelar</button><button className="rounded-lg bg-[#800020] px-4 py-2 text-xs font-bold text-white">Guardar cambios</button></div></form>}
    {addCopyBookId && <form onSubmit={addCopy} className="grid gap-3 rounded-xl border bg-white p-5 md:grid-cols-3"><h3 className="font-bold md:col-span-3">Agregar ejemplar</h3><input required value={addCopyForm.barcode} onChange={(e) => setAddCopyForm({ ...addCopyForm, barcode: e.target.value })} placeholder="Código de barras / QR" className="rounded-lg border px-3 py-2 text-sm"/><input value={addCopyForm.location} onChange={(e) => setAddCopyForm({ ...addCopyForm, location: e.target.value })} placeholder="Ubicación" className="rounded-lg border px-3 py-2 text-sm"/><div className="flex justify-end gap-2"><button type="button" onClick={() => setAddCopyBookId(null)} className="rounded-lg border px-4 py-2 text-xs">Cancelar</button><button className="rounded-lg bg-[#800020] px-4 py-2 text-xs font-bold text-white">Agregar</button></div></form>}
    {editCopy && <form onSubmit={saveCopyStatus} className="grid gap-3 rounded-xl border bg-white p-5 md:grid-cols-4"><h3 className="font-bold md:col-span-4">Editar ejemplar · {editCopy.bookTitle}</h3><select value={editCopy.status} onChange={(e) => setEditCopy({ ...editCopy, status: e.target.value })} className="rounded-lg border px-3 py-2 text-sm"><option value="DISPONIBLE">DISPONIBLE</option><option value="MANTENIMIENTO">MANTENIMIENTO</option><option value="FUERA_CIRCULACION">FUERA_CIRCULACION</option></select><select value={editCopy.condition} onChange={(e) => setEditCopy({ ...editCopy, condition: e.target.value })} className="rounded-lg border px-3 py-2 text-sm"><option value="BUENO">BUENO</option><option value="REGULAR">REGULAR</option><option value="DAÑADO">DAÑADO</option></select><input value={editCopy.location} onChange={(e) => setEditCopy({ ...editCopy, location: e.target.value })} placeholder="Ubicación" className="rounded-lg border px-3 py-2 text-sm"/><div className="flex justify-end gap-2"><button type="button" onClick={() => setEditCopy(null)} className="rounded-lg border px-4 py-2 text-xs">Cancelar</button><button className="rounded-lg bg-[#800020] px-4 py-2 text-xs font-bold text-white">Guardar</button></div></form>}
    <Pagination currentPage={bookPage} totalPages={Math.max(1, Math.ceil(filtered.length / bookPageSize))} totalItems={filtered.length} pageSize={bookPageSize} onPageChange={setBookPage} pageSizeOptions={[10, 20, 50, 100]} onPageSizeChange={(s) => { setBookPageSize(s); setBookPage(1); }} />
    <div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{paginatedBooks.map((book) => <article key={book.id} className="rounded-xl border bg-white p-5 shadow-xs"><div className="flex items-start justify-between"><div className="rounded-lg bg-[#800020]/10 p-2 text-[#800020]"><Library className="h-5 w-5"/></div><div className="flex items-center gap-2"><span className={`rounded-full px-2 py-1 text-[10px] font-bold ${book.available ? 'bg-green-100 text-green-700' : 'bg-amber-100 text-amber-700'}`}>{book.available}/{book.totalCopies} disponibles</span>{staff && <button type="button" onClick={() => { setEditBook(book); setEditBookForm({ title: book.title, author: book.author, category: book.category, isbn: book.isbn || '', publisher: '' }); setAddCopyBookId(null); setEditCopy(null); }} className="rounded-lg border px-2 py-1 text-[10px] font-bold text-[#800020] hover:bg-[#800020]/10"><Edit2 className="inline h-3 w-3 mr-1"/>Editar</button>}{staff && <button type="button" onClick={() => { setAddCopyBookId(book.id); setAddCopyForm({ barcode: '', location: 'Biblioteca Central' }); setEditBook(null); setEditCopy(null); }} className="rounded-lg border px-2 py-1 text-[10px] font-bold hover:bg-slate-50"><CopyPlus className="inline h-3 w-3 mr-1"/>Ejemplar</button>}</div></div><h3 className="mt-3 font-bold">{book.title}</h3><p className="text-xs text-[#64748B]">{book.author}</p><p className="mt-2 text-[10px] font-bold uppercase text-[#800020]">{book.category}</p><div className="mt-4 border-t pt-3 text-[10px] text-[#64748B] space-y-1">{book.copies.map((copy) => <div key={copy.id} className="flex items-center justify-between"><span>{copy.barcode} · {copy.location} · {copy.status}</span>{staff && <button type="button" onClick={() => { setEditCopy({ id: copy.id, bookTitle: book.title, status: copy.status, condition: copy.condition, location: copy.location }); setEditBook(null); setAddCopyBookId(null); }} className="ml-2 rounded border px-1.5 py-0.5 text-[9px] font-bold text-[#800020] hover:bg-[#800020]/10">Editar</button>}</div>)}</div>{!staff && <button onClick={() => action(`/api/library/books/${book.id}/reserve`, book.available ? 'Solicitud en línea registrada; pasa a recogerlo en 48 horas' : 'Reserva registrada por 48 horas')} className="mt-3 w-full rounded-lg border border-[#800020] px-3 py-2 text-xs font-bold text-[#800020]">{book.available ? 'Solicitar préstamo en línea' : 'Reservar cuando esté disponible'}</button>}</article>)}</div>
    <section className="rounded-xl border bg-white p-5 shadow-xs"><div className="mb-3 flex items-center justify-between"><h2 className="font-bold">{staff?'Solicitudes en línea':'Mis solicitudes'}</h2><span className="text-xs text-[#64748B]">{reservations.filter((item)=>['ACTIVA','SOLICITADA','LISTA'].includes(item.status)).length} activas</span></div>{reservations.length===0?<p className="py-5 text-center text-xs text-[#64748B]">No hay solicitudes registradas.</p>:<div className="overflow-x-auto"><table className="w-full text-left text-xs"><thead className="bg-[#F8FAFC]"><tr><th className="p-3">Libro</th>{staff&&<th className="p-3">Solicitante</th>}<th className="p-3">Estado</th><th className="p-3">Plazo</th><th className="p-3">Ejemplar</th><th className="p-3"></th></tr></thead><tbody className="divide-y">{reservations.map((item)=>{const copy=books.flatMap((book)=>book.copies).find((entry)=>entry.id===item.assignedCopyId);return <tr key={item.id}><td className="p-3 font-bold">{item.book.title}</td>{staff&&<td className="p-3">{item.user.carnetOrCode||item.user.email} · {item.user.name}</td>}<td className="p-3"><span className={`rounded-full px-2 py-1 text-[9px] font-bold ${item.status==='LISTA'?'bg-green-100 text-green-700':item.status==='SOLICITADA'||item.status==='ACTIVA'?'bg-blue-100 text-blue-700':'bg-slate-100 text-slate-600'}`}>{item.status}</span></td><td className="p-3">{new Date(item.expiresAt).toLocaleString('es-GT')}</td><td className="p-3 font-mono">{copy?.barcode||'Pendiente'}</td><td className="p-3 text-right">{['ACTIVA','SOLICITADA','LISTA'].includes(item.status)&&<div className="flex justify-end gap-2">{staff&&['ACTIVA','SOLICITADA'].includes(item.status)&&<button onClick={()=>action(`/api/library/reservations/${item.id}/prepare`,'Ejemplar preparado y alumno notificado')} className="font-bold text-green-700">Preparar</button>}<button onClick={()=>post(`/api/library/reservations/${item.id}/cancel`,{},'PATCH').then((result)=>{if(result){showToast('Solicitud cancelada y ejemplar liberado','success');load();}})} className="font-bold text-red-700">Cancelar</button></div>}</td></tr>})}</tbody></table></div>}</section>
    <section className="rounded-xl border bg-white p-5 shadow-xs"><h2 className="mb-3 font-bold">{staff ? 'Préstamos recientes' : 'Mis préstamos'}</h2>{loans.length === 0 ? <p className="py-5 text-center text-xs text-[#64748B]">No hay préstamos registrados.</p> : <div className="overflow-x-auto"><table className="w-full text-left text-xs"><thead className="bg-[#F8FAFC] text-[10px] uppercase text-[#64748B]"><tr><th className="p-3">Libro</th>{staff && <th className="p-3">Usuario</th>}<th className="p-3">Vencimiento</th><th className="p-3">Estado</th><th className="p-3"></th></tr></thead><tbody className="divide-y">{loans.map((loan) => <tr key={loan.id}><td className="p-3"><p className="font-bold">{loan.bookTitle}</p><p className="text-[10px] text-[#64748B]">{loan.barcode}</p></td>{staff && <td className="p-3"><p>{loan.borrowerCode} · {loan.borrowerName}</p>{loan.suspendedUntil&&new Date(loan.suspendedUntil)>new Date()&&<button onClick={()=>post(`/api/library/users/${loan.borrowerId}/suspension`,{},'PATCH').then((result)=>{if(result){showToast('Suspensión levantada','success');load();}})} className="mt-1 text-[9px] font-bold text-red-700">Suspendido hasta {new Date(loan.suspendedUntil).toLocaleDateString('es-GT')} · Levantar</button>}</td>}<td className="p-3">{new Date(loan.dueAt).toLocaleDateString('es-GT')}</td><td className="p-3"><span className={`rounded-full px-2 py-1 text-[10px] font-bold ${loan.status === 'VENCIDO' ? 'bg-red-100 text-red-700' : ['DEVUELTO','DANADO','PERDIDO'].includes(loan.status) ? 'bg-slate-100 text-slate-600' : 'bg-blue-100 text-blue-700'}`}>{loan.status}</span></td><td className="p-3 text-right">{['PRESTADO','VENCIDO'].includes(loan.status) && <div className="flex justify-end gap-2">{loan.renewalCount < 1 && <button onClick={() => action(`/api/library/loans/${loan.id}/renew`, 'Préstamo renovado 7 días')} className="font-bold text-blue-700"><RotateCcw className="mr-1 inline h-3.5 w-3.5"/>Renovar</button>}{staff && <button onClick={() => action(`/api/library/loans/${loan.id}/return`, 'Devolución registrada')} className="font-bold text-green-700"><CheckCircle2 className="mr-1 inline h-3.5 w-3.5"/>Devolver</button>}{staff&&<button onClick={()=>{setSelectedLoan(loan);setPanel('INCIDENT');}} className="font-bold text-red-700">Incidencia</button>}</div>}</td></tr>)}</tbody></table></div>}</section>
    {scanTarget && <QrScanner onScan={(value)=>setLoanForm(scanTarget === 'BORROWER' ? {...loanForm,borrowerCode:value} : {...loanForm,barcode:value})} onClose={()=>setScanTarget(null)}/>}
  </div></RoleGuard>;
};
