import React, { useEffect, useState } from 'react';
import { Activity, KeyRound, MailWarning, RefreshCw, ShieldCheck, Wrench } from 'lucide-react';
import { PageHeader } from '../components/common/PageHeader';
import { RoleGuard } from '../components/common/RoleGuard';
import { useApp } from '../context/AppContext';

type Account = { id: string; name: string; email: string; role: string; active: boolean; mustChangePassword: boolean; mfaEnabled: boolean };
type Audit = { id: string; action: string; entityType: string; actor: string; actorRole: string | null; createdAt: string };
type Outbox = { id: string; recipientEmail: string; subject: string; status: string; attempts: number; lastError?: string | null; createdAt: string };
type Overview = { health: { ok: boolean; database: string; smtpConfigured: boolean }; metrics: { managedUsers: number; activeSessions: number; mfaEnabled: number; pendingEmails: number; failedEmails: number }; audit: Audit[] };

export const SystemsPage: React.FC = () => {
  const { showToast } = useApp();
  const [overview, setOverview] = useState<Overview | null>(null);
  const [accounts, setAccounts] = useState<Account[]>([]);
  const [outbox, setOutbox] = useState<Outbox[]>([]);
  const [busy, setBusy] = useState('');
  const load = async () => {
    const [overviewResponse, accountsResponse, outboxResponse] = await Promise.all([fetch('/api/systems/overview'), fetch('/api/systems/accounts'), fetch('/api/systems/outbox')]);
    if (![overviewResponse, accountsResponse, outboxResponse].every((response) => response.ok)) return showToast('No se pudo cargar la operación técnica.', 'error');
    setOverview(await overviewResponse.json()); setAccounts(await accountsResponse.json()); setOutbox((await outboxResponse.json()).records);
  };
  useEffect(() => { void load(); }, []);
  const support = async (id: string, action: 'reset-password' | 'reset-mfa') => {
    setBusy(`${action}-${id}`);
    const response = await fetch(`/api/systems/accounts/${id}/${action}`, { method: 'POST' });
    const result = await response.json(); setBusy('');
    if (!response.ok) return showToast(result.message || 'No se pudo completar el soporte.', 'error');
    if (action === 'reset-password') showToast(`Contraseña temporal: ${result.temporaryPassword}`, 'success'); else showToast('MFA restablecido; el usuario deberá configurarlo de nuevo.', 'success');
    await load();
  };
  const retry = async (id: string) => { setBusy(`retry-${id}`); const response = await fetch(`/api/systems/outbox/${id}/retry`, { method: 'POST' }); const result = await response.json(); setBusy(''); if (!response.ok) return showToast(result.message || 'No se pudo reintentar el correo.', 'error'); showToast(`Correo procesado: ${result.status}`, 'success'); await load(); };
  return <RoleGuard allowedRoles={['SISTEMAS']}><div className="space-y-6"><PageHeader title="Operación de Sistemas" description="Monitoreo, auditoría y soporte técnico con privilegios restringidos" breadcrumbs={[{ label: 'Inicio', href: '/dashboard' }, { label: 'Sistemas', active: true }]} actions={<button onClick={() => void load()} className="flex items-center gap-2 rounded-lg border bg-white px-4 py-2 text-xs font-bold"><RefreshCw className="h-4 w-4" />Actualizar</button>} />
    {!overview ? <div className="rounded-xl border bg-white p-8 text-center text-sm text-slate-500">Cargando estado del sistema...</div> : <><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-5"><Stat label="Estado" value={overview.health.ok ? 'Operativo' : 'Revisar'} icon={Activity} tone="green" /><Stat label="Sesiones activas" value={overview.metrics.activeSessions} icon={ShieldCheck} tone="blue" /><Stat label="Cuentas atendibles" value={overview.metrics.managedUsers} icon={Wrench} tone="maroon" /><Stat label="MFA habilitado" value={overview.metrics.mfaEnabled} icon={ShieldCheck} tone="green" /><Stat label="Correos pendientes" value={overview.metrics.pendingEmails} icon={MailWarning} tone="amber" /></div>
      <div className="grid gap-4 lg:grid-cols-2"><section className="rounded-xl border bg-white p-5 shadow-xs"><h2 className="text-sm font-bold">Servicios</h2><dl className="mt-4 space-y-3 text-xs"><Row label="Base de datos" value={overview.health.database} /><Row label="SMTP" value={overview.health.smtpConfigured ? 'Configurado' : 'Pendiente de configuración'} /><Row label="Correos fallidos" value={String(overview.metrics.failedEmails)} /></dl></section><section className="rounded-xl border bg-white p-5 shadow-xs"><h2 className="text-sm font-bold">Restricción del rol</h2><p className="mt-3 text-xs leading-5 text-slate-600">Este rol no puede administrar usuarios ADMIN, política MFA, institución, datos académicos, pagos ni comunicaciones masivas. Todas las acciones de soporte quedan auditadas.</p></section></div>
      <section className="overflow-hidden rounded-xl border bg-white shadow-xs"><div className="border-b p-5"><h2 className="text-sm font-bold">Soporte de cuentas</h2><p className="mt-1 text-xs text-slate-500">Solo cuentas no administrativas.</p></div><div className="overflow-x-auto"><table className="w-full text-left text-xs"><thead className="bg-slate-50 text-[10px] uppercase text-slate-500"><tr><th className="p-3">Usuario</th><th className="p-3">Rol</th><th className="p-3">Seguridad</th><th className="p-3 text-right">Soporte</th></tr></thead><tbody className="divide-y">{accounts.map((account) => <tr key={account.id}><td className="p-3"><p className="font-bold">{account.name}</p><p className="text-[10px] text-slate-500">{account.email}</p></td><td className="p-3 font-bold">{account.role}</td><td className="p-3">MFA {account.mfaEnabled ? 'activo' : 'inactivo'}{account.mustChangePassword ? ' · cambio pendiente' : ''}</td><td className="p-3"><div className="flex justify-end gap-2"><button disabled={Boolean(busy)} onClick={() => void support(account.id, 'reset-password')} className="rounded-lg border px-3 py-2 font-bold text-[#800020] disabled:opacity-50"><KeyRound className="mr-1 inline h-3.5 w-3.5" />Contraseña</button><button disabled={Boolean(busy) || !account.mfaEnabled} onClick={() => void support(account.id, 'reset-mfa')} className="rounded-lg border px-3 py-2 font-bold text-red-700 disabled:opacity-50">MFA</button></div></td></tr>)}</tbody></table></div></section>
      <div className="grid gap-4 xl:grid-cols-2"><section className="overflow-hidden rounded-xl border bg-white shadow-xs"><div className="border-b p-5"><h2 className="text-sm font-bold">Cola de correo con incidencias</h2></div>{outbox.length === 0 ? <p className="p-5 text-xs text-slate-500">No hay correos pendientes o fallidos.</p> : <div className="divide-y">{outbox.map((email) => <div key={email.id} className="flex items-center justify-between gap-3 p-4 text-xs"><div className="min-w-0"><p className="truncate font-bold">{email.subject}</p><p className="truncate text-slate-500">{email.recipientEmail} · {email.status} · intento {email.attempts}</p>{email.lastError && <p className="mt-1 text-red-700">{email.lastError}</p>}</div><button disabled={Boolean(busy)} onClick={() => void retry(email.id)} className="shrink-0 rounded-lg border px-3 py-2 font-bold disabled:opacity-50">Reintentar</button></div>)}</div>}</section><section className="overflow-hidden rounded-xl border bg-white shadow-xs"><div className="border-b p-5"><h2 className="text-sm font-bold">Auditoría reciente</h2></div><div className="divide-y">{overview.audit.map((record) => <div key={record.id} className="p-3 text-xs"><p className="font-bold">{record.action}</p><p className="text-slate-500">{record.entityType} · {record.actor} {record.actorRole ? `(${record.actorRole})` : ''} · {new Date(record.createdAt).toLocaleString('es-GT')}</p></div>)}</div></section></div></>}</div></RoleGuard>;
};

const Stat = ({ label, value, icon: Icon, tone }: { label: string; value: string | number; icon: React.ElementType; tone: string }) => <div className="rounded-xl border bg-white p-4 shadow-xs"><div className={`mb-2 w-fit rounded-lg p-2 ${tone === 'green' ? 'bg-green-50 text-green-700' : tone === 'amber' ? 'bg-amber-50 text-amber-700' : tone === 'blue' ? 'bg-blue-50 text-blue-700' : 'bg-[#800020]/10 text-[#800020]'}`}><Icon className="h-4 w-4" /></div><p className="text-xl font-extrabold">{value}</p><p className="text-[11px] text-slate-500">{label}</p></div>;
const Row = ({ label, value }: { label: string; value: string }) => <div className="flex justify-between gap-4 border-b pb-2 last:border-0"><dt className="text-slate-500">{label}</dt><dd className="font-bold">{value}</dd></div>;
