import React, { useEffect, useMemo, useState } from 'react';
import { KeyRound, Plus, RefreshCw, Search, ShieldOff, Users } from 'lucide-react';
import { PageHeader } from '../components/common/PageHeader';
import { PasswordInput } from '../components/common/PasswordInput';
import { useApp } from '../context/AppContext';

type ManagedUser = { id: string; name: string; email: string; role: string; carnetOrCode?: string; active: boolean; mustChangePassword: boolean; mfaEnabled: boolean };

export const UsersPage: React.FC = () => {
  const { currentUser, showToast } = useApp();
  const [users, setUsers] = useState<ManagedUser[]>([]);
  const [search, setSearch] = useState('');
  const [busyId, setBusyId] = useState('');
  const [credential, setCredential] = useState<{ name: string; password: string } | null>(null);
  const [showCreate, setShowCreate] = useState(false);
  const [newUser, setNewUser] = useState({ name: '', email: '', role: 'ADMIN', carnetOrCode: '' });
  const load = async () => { const response = await fetch('/api/admin/users'); if (response.ok) setUsers(await response.json()); };
  useEffect(() => { void load(); }, []);
  const filtered = useMemo(() => { const value = search.toLowerCase(); return users.filter((user) => [user.name, user.email, user.role, user.carnetOrCode || ''].some((field) => field.toLowerCase().includes(value))); }, [users, search]);
  const createUser = async (event: React.FormEvent) => { event.preventDefault(); const response = await fetch('/api/admin/users', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(newUser) }); const result = await response.json(); if (!response.ok) return showToast(result.message || 'No se pudo crear el usuario', 'error'); setCredential({ name: result.user.name, password: result.temporaryPassword }); setNewUser({ name: '', email: '', role: 'ADMIN', carnetOrCode: '' }); setShowCreate(false); showToast('Usuario creado correctamente', 'success'); await load(); };
  const resetPassword = async (user: ManagedUser) => { setBusyId(user.id); const response = await fetch(`/api/admin/users/${user.id}/reset-password`, { method: 'POST' }); const result = await response.json(); setBusyId(''); if (!response.ok) return showToast(result.message, 'error'); setCredential({ name: user.name, password: result.temporaryPassword }); showToast('Contraseña temporal generada', 'success'); await load(); };
  const resetMfa = async (user: ManagedUser) => { setBusyId(user.id); const response = await fetch(`/api/admin/users/${user.id}/reset-mfa`, { method: 'POST' }); const result = await response.json(); setBusyId(''); if (!response.ok) return showToast(result.message, 'error'); showToast('MFA restablecido', 'success'); await load(); };
  return <div className="space-y-6"><PageHeader title="Usuarios y Seguridad" description="Creación de usuarios, contraseñas, sesiones y MFA" breadcrumbs={[{ label: 'Inicio', href: '/dashboard' }, { label: 'Usuarios y Seguridad', active: true }]} actions={<button onClick={() => setShowCreate((value) => !value)} className="flex items-center gap-2 rounded-lg bg-[#800020] px-4 py-2 text-xs font-bold text-white"><Plus className="h-4 w-4" />Nuevo usuario</button>} />
    {showCreate && <form onSubmit={createUser} className="grid gap-3 rounded-xl border border-[#800020]/20 bg-white p-5 md:grid-cols-4"><input required minLength={3} value={newUser.name} onChange={(e) => setNewUser({ ...newUser, name: e.target.value })} placeholder="Nombre completo" className="rounded-lg border px-3 py-2 text-xs" /><input required type="email" value={newUser.email} onChange={(e) => setNewUser({ ...newUser, email: e.target.value })} placeholder="Correo institucional" className="rounded-lg border px-3 py-2 text-xs" /><select value={newUser.role} onChange={(e) => setNewUser({ ...newUser, role: e.target.value })} className="rounded-lg border px-3 py-2 text-xs"><option>ADMIN</option><option>DOCENTE</option><option>ESTUDIANTE</option><option>BIBLIOTECA</option><option>PARQUEO</option><option>EVENTOS</option><option>SISTEMAS</option></select><input value={newUser.carnetOrCode} onChange={(e) => setNewUser({ ...newUser, carnetOrCode: e.target.value })} placeholder="Carné o código (opcional)" className="rounded-lg border px-3 py-2 text-xs" /><div className="flex justify-end gap-2 md:col-span-4"><button type="button" onClick={() => setShowCreate(false)} className="rounded-lg border px-4 py-2 text-xs font-bold">Cancelar</button><button className="rounded-lg bg-[#800020] px-4 py-2 text-xs font-bold text-white">Crear usuario</button></div></form>}
    {credential && <div className="rounded-xl border border-amber-300 bg-amber-50 p-5"><p className="text-sm font-bold text-amber-950">Contraseña temporal para {credential.name}</p><p className="mt-1 text-xs text-amber-800">Cópiala ahora; el usuario deberá cambiarla al ingresar.</p><PasswordInput readOnly value={credential.password} aria-label="Contraseña temporal" className="mt-3 w-full max-w-md rounded-lg border border-amber-300 bg-white px-3 py-2 font-mono font-bold" /></div>}
    <div className="rounded-xl border bg-white shadow-xs"><div className="flex flex-col gap-3 border-b p-5 sm:flex-row sm:items-center sm:justify-between"><div className="flex items-center gap-2"><Users className="h-5 w-5 text-[#800020]" /><h2 className="text-sm font-bold">Directorio de usuarios</h2></div><div className="relative"><Search className="absolute left-3 top-2.5 h-4 w-4 text-[#64748B]" /><input value={search} onChange={(e) => setSearch(e.target.value)} placeholder="Buscar usuario..." className="rounded-lg border py-2 pl-9 pr-3 text-xs" /></div></div><div className="overflow-x-auto"><table className="w-full text-left text-xs"><thead className="bg-[#F8FAFC] text-[10px] uppercase text-[#64748B]"><tr><th className="p-3">Usuario</th><th className="p-3">Rol</th><th className="p-3">Seguridad</th><th className="p-3 text-right">Acciones</th></tr></thead><tbody className="divide-y">{filtered.map((user) => <tr key={user.id}><td className="p-3"><p className="font-bold">{user.name}</p><p className="text-[10px] text-[#64748B]">{user.email}{user.carnetOrCode ? ` · ${user.carnetOrCode}` : ''}</p></td><td className="p-3 font-bold">{user.role}</td><td className="p-3"><span className={`rounded-full px-2 py-1 text-[10px] font-bold ${user.mfaEnabled ? 'bg-green-100 text-green-800' : 'bg-slate-100 text-slate-700'}`}>MFA {user.mfaEnabled ? 'activo' : 'inactivo'}</span>{user.mustChangePassword && <span className="ml-2 rounded-full bg-amber-100 px-2 py-1 text-[10px] font-bold text-amber-800">Cambio pendiente</span>}</td><td className="p-3"><div className="flex justify-end gap-2"><button disabled={busyId === user.id || user.id === currentUser.id} onClick={() => resetPassword(user)} className="flex items-center gap-1 rounded-lg border px-3 py-2 font-bold text-[#800020] disabled:opacity-40"><KeyRound className="h-3.5 w-3.5" />Contraseña</button><button disabled={busyId === user.id || !user.mfaEnabled || user.id === currentUser.id} onClick={() => resetMfa(user)} className="flex items-center gap-1 rounded-lg border px-3 py-2 font-bold text-red-700 disabled:opacity-40"><ShieldOff className="h-3.5 w-3.5" />MFA</button></div></td></tr>)}</tbody></table>{filtered.length === 0 && <div className="p-8 text-center text-xs text-[#64748B]"><RefreshCw className="mx-auto mb-2 h-5 w-5" />No se encontraron usuarios.</div>}</div></div>
  </div>;
};
