import React, { useState } from 'react';
import { MessageCircle, Send, X } from 'lucide-react';

export const AcademicAssistant: React.FC = () => {
  const [open, setOpen] = useState(false);
  const [question, setQuestion] = useState('');
  const [messages, setMessages] = useState<{ from: 'user' | 'bot'; text: string }[]>([{ from: 'bot', text: 'Hola. Puedo ayudarte con información académica de tu cuenta.' }]);
  const [loading, setLoading] = useState(false);
  const ask = async (event: React.FormEvent) => { event.preventDefault(); const value = question.trim(); if (!value || loading) return; setQuestion(''); setMessages((current) => [...current, { from: 'user', text: value }]); setLoading(true); try { const response = await fetch('/api/assistant', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ question: value }) }); const result = await response.json(); setMessages((current) => [...current, { from: 'bot', text: response.ok ? result.answer : result.message || 'No pude responder.' }]); } catch { setMessages((current) => [...current, { from: 'bot', text: 'No se pudo conectar con el asistente.' }]); } finally { setLoading(false); } };
  return <div className="fixed bottom-5 right-5 z-50">{open && <div className="mb-3 flex h-[min(520px,70vh)] w-[min(360px,calc(100vw-2rem))] flex-col overflow-hidden rounded-2xl border border-[#E2E8F0] bg-white shadow-2xl"><div className="flex items-center justify-between bg-[#800020] px-4 py-3 text-white"><div><p className="text-sm font-extrabold">Asistente académico</p><p className="text-[10px] text-white/75">Información de tu cuenta</p></div><button type="button" onClick={() => setOpen(false)} aria-label="Cerrar asistente"><X className="h-4 w-4" /></button></div><div className="flex-1 space-y-3 overflow-auto bg-[#F8FAFC] p-3">{messages.map((message, index) => <div key={`${message.from}-${index}`} className={`whitespace-pre-line rounded-xl px-3 py-2 text-xs ${message.from === 'user' ? 'ml-8 bg-[#800020] text-white' : 'mr-5 bg-white text-[#333333] shadow-sm'}`}>{message.text}</div>)}{loading && <div className="text-xs text-[#64748B]">Consultando tus datos...</div>}</div><form onSubmit={ask} className="flex gap-2 border-t p-3"><input value={question} onChange={(event) => setQuestion(event.target.value)} placeholder="¿Qué quieres consultar?" className="min-w-0 flex-1 rounded-lg border px-3 py-2 text-xs" /><button type="submit" disabled={loading} aria-label="Enviar pregunta" className="rounded-lg bg-[#800020] px-3 text-white disabled:opacity-50"><Send className="h-4 w-4" /></button></form></div>}<button type="button" onClick={() => setOpen((value) => !value)} aria-label="Abrir asistente académico" className="flex h-14 w-14 items-center justify-center rounded-full bg-[#800020] text-white shadow-xl transition hover:bg-[#5F0018]"><MessageCircle className="h-6 w-6" /></button></div>;
};
